import type { WebCard, Category } from "./types";

export const defaultCategories: Category[] = [
  { id: "cat-1", name: "常用", icon: "star", color: "#B8860B", order: 0, createdAt: Date.now() },
  { id: "cat-2", name: "AI 工具", icon: "wrench", color: "#4A6FA5", order: 1, createdAt: Date.now() },
  { id: "cat-3", name: "设计灵感", icon: "palette", color: "#9B7E8E", order: 2, createdAt: Date.now() },
  { id: "cat-4", name: "开发者", icon: "code", color: "#4A7C59", order: 3, createdAt: Date.now() },
  { id: "cat-5", name: "阅读", icon: "book-open", color: "#8B6F5C", order: 4, createdAt: Date.now() },
];

export const defaultCards: WebCard[] = [
  {
    id: "card-1",
    url: "https://chat.openai.com",
    title: "ChatGPT",
    shortDesc: "智能对话助手",
    fullDesc: "OpenAI 推出的对话式 AI，支持代码编写、创意写作、知识问答等多种任务。",
    note: "日常查询首选",
    abbreviation: "GPT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    categoryId: "cat-2",
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-2",
    url: "https://claude.ai",
    title: "Claude",
    shortDesc: "Anthropic AI",
    fullDesc: "Anthropic 开发的 AI 助手，以长文本理解和安全性著称。",
    note: "长文阅读用",
    abbreviation: "Claude",
    imageUrl: "",
    categoryId: "cat-2",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-3",
    url: "https://www.figma.com",
    title: "Figma",
    shortDesc: "协作设计工具",
    fullDesc: "基于浏览器的界面设计工具，支持实时多人协作和原型制作。",
    note: "UI 设计必备",
    abbreviation: "Figma",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg",
    categoryId: "cat-3",
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-4",
    url: "https://dribbble.com",
    title: "Dribbble",
    shortDesc: "设计师社区",
    fullDesc: "全球设计师分享作品的平台，涵盖 UI、插画、品牌等多种创意领域。",
    note: "灵感来源",
    abbreviation: "Dribbble",
    imageUrl: "",
    categoryId: "cat-3",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-5",
    url: "https://github.com",
    title: "GitHub",
    shortDesc: "代码托管平台",
    fullDesc: "全球最大的代码托管和协作开发平台，支持 Git 版本控制。",
    note: "代码仓库",
    abbreviation: "GH",
    imageUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
    categoryId: "cat-4",
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-6",
    url: "https://stackoverflow.com",
    title: "Stack Overflow",
    shortDesc: "开发者问答",
    fullDesc: "程序员问答社区，几乎可以找到所有编程问题的解决方案。",
    note: "查 bug 专用",
    abbreviation: "SO",
    imageUrl: "",
    categoryId: "cat-4",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-7",
    url: "https://www.notion.so",
    title: "Notion",
    shortDesc: "全能工作空间",
    fullDesc: "集笔记、数据库、看板、日历于一体的一站式工作管理平台。",
    note: "知识管理",
    abbreviation: "Notion",
    imageUrl: "",
    categoryId: "cat-1",
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-8",
    url: "https://www.google.com",
    title: "Google",
    shortDesc: "搜索引擎",
    fullDesc: "全球最常用的搜索引擎，提供网页、图片、地图等全方位搜索服务。",
    note: "日常搜索",
    abbreviation: "Google",
    imageUrl: "",
    categoryId: "cat-1",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-9",
    url: "https://www.are.na",
    title: "Are.na",
    shortDesc: "灵感收集板",
    fullDesc: "一个用于研究和创意思考的协作平台，以区块方式组织链接和图片。",
    note: "收藏灵感",
    abbreviation: "Are.na",
    imageUrl: "",
    categoryId: "cat-3",
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "card-10",
    url: "https://juejin.cn",
    title: "稀土掘金",
    shortDesc: "技术社区",
    fullDesc: "中文开发者社区，涵盖前端、后端、移动端等技术领域的优质文章。",
    note: "中文技术阅读",
    abbreviation: "掘金",
    imageUrl: "",
    categoryId: "cat-5",
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
