import type { WallpaperItem } from "./wallpaper-types";

type CuratedWallpaper = Omit<WallpaperItem, "fetchedAt">;

function curated(item: CuratedWallpaper): WallpaperItem {
  return {
    ...item,
    fetchedAt: 0,
  };
}

export const ZOOM_CURATED_WALLPAPERS: WallpaperItem[] = [
  curated({
    id: "zoom-nasa-cosmic-cliffs",
    title: "Cosmic Cliffs in the Carina Nebula",
    author: "NASA, ESA, CSA, STScI",
    source: "nasa",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:NASA%E2%80%99s_Webb_Reveals_Cosmic_Cliffs,_Glittering_Landscape_of_Star_Birth.jpg",
    imageUrl: "/assets/wallpapers/zoom-nasa-cosmic-cliffs.jpg",
    thumbnailUrl: "/assets/wallpapers/zoom-nasa-cosmic-cliffs.jpg",
    license: "Public domain / NASA",
    width: 5000,
    height: 2895,
    category: "space",
    quality: "award",
    sourceCollection: "NASA / Wikimedia Picture of the Year finalist",
    quoteId: "mountain-rain",
  }),
  curated({
    id: "zoom-eso-milky-way",
    title: "Milky Way panorama",
    author: "ESO / S. Brunier",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ESO_-_Milky_Way.jpg",
    imageUrl: "/assets/wallpapers/zoom-eso-milky-way.jpg",
    thumbnailUrl: "/assets/wallpapers/zoom-eso-milky-way.jpg",
    license: "Creative Commons Attribution 4.0",
    width: 6000,
    height: 3000,
    category: "space",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Pictures / ESO",
    quoteId: "quiet-horizon",
  }),
  curated({
    id: "zoom-nasa-blue-marble",
    title: "Blue Marble 2002",
    author: "NASA Goddard Space Flight Center",
    source: "nasa",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Blue_Marble_2002.png",
    imageUrl: "/assets/wallpapers/zoom-nasa-blue-marble.png",
    thumbnailUrl: "/assets/wallpapers/zoom-nasa-blue-marble.png",
    license: "Public domain / NASA",
    width: 43200,
    height: 21600,
    category: "aerial",
    quality: "featured",
    sourceCollection: "NASA Visible Earth / Wikimedia Featured Pictures",
    quoteId: "single-earth",
  }),
  curated({
    id: "zoom-hubble-carina-panorama",
    title: "Hubble Carina Nebula panorama",
    author: "NASA, ESA, N. Smith, Hubble Heritage Team",
    source: "nasa",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:NGC_3372a-full.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f8/NGC_3372a-full.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f8/NGC_3372a-full.jpg",
    license: "Public domain / NASA",
    width: 29566,
    height: 14321,
    category: "space",
    quality: "award",
    sourceCollection: "NASA / Hubble Featured Pictures",
    quoteId: "cosmic-patience",
  }),
  curated({
    id: "zoom-eso-carina-nebula",
    title: "The Carina Nebula",
    author: "ESO / R. Gendler, J-E. Ovaldsen, C. Thone, C. Feron",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ESO_-_The_Carina_Nebula_(by).jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/ESO_-_The_Carina_Nebula_%28by%29.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/ESO_-_The_Carina_Nebula_%28by%29.jpg",
    license: "Creative Commons Attribution 4.0",
    width: 5828,
    height: 3524,
    category: "space",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Pictures / ESO",
    quoteId: "cosmic-patience",
  }),
  curated({
    id: "zoom-wle-madygen-geopark",
    title: "Madygen Geopark colors",
    author: "Marat Nadjibaev",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%93%D0%B5%D0%BE%D0%BF%D0%B0%D1%80%D0%BA_%D0%9C%D0%B0%D0%B4%D1%8B%D0%B3%D0%B5%D0%BD_(%D0%BA%D1%80%D0%B0%D1%81%D0%BA%D0%B8).jpg",
    imageUrl: "/assets/wallpapers/zoom-wle-madygen-geopark.jpg",
    thumbnailUrl: "/assets/wallpapers/zoom-wle-madygen-geopark.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 5000,
    height: 2812,
    category: "landscape",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 winners",
    quoteId: "old-stone",
  }),
  curated({
    id: "zoom-wle-karynzharyk-valley",
    title: "Karynzharyk depression at distance",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9C%D0%B0%D1%80%D1%81%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%B5%D0%B9%D0%B7%D0%B0%D0%B6_%D0%B2%D0%BF%D0%B0%D0%B4%D0%B8%D0%BD%D1%8B_%D0%9A%D0%B0%D1%80%D1%8B%D0%BD%D0%B6%D0%B0%D1%80%D1%8B%D0%BA._%D0%92%D0%B4%D0%B0%D0%BB%D0%B8_%D0%A2%D1%80%D0%B8_%D0%91%D0%B0%D1%82%D1%8B%D1%80%D0%B0.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b1/%D0%9C%D0%B0%D1%80%D1%81%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%B5%D0%B9%D0%B7%D0%B0%D0%B6_%D0%B2%D0%BF%D0%B0%D0%B4%D0%B8%D0%BD%D1%8B_%D0%9A%D0%B0%D1%80%D1%8B%D0%BD%D0%B6%D0%B0%D1%80%D1%8B%D0%BA._%D0%92%D0%B4%D0%B0%D0%BB%D0%B8_%D0%A2%D1%80%D0%B8_%D0%91%D0%B0%D1%82%D1%8B%D1%80%D0%B0.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b1/%D0%9C%D0%B0%D1%80%D1%81%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%B5%D0%B9%D0%B7%D0%B0%D0%B6_%D0%B2%D0%BF%D0%B0%D0%B4%D0%B8%D0%BD%D1%8B_%D0%9A%D0%B0%D1%80%D1%8B%D0%BD%D0%B6%D0%B0%D1%80%D1%8B%D0%BA._%D0%92%D0%B4%D0%B0%D0%BB%D0%B8_%D0%A2%D1%80%D0%B8_%D0%91%D0%B0%D1%82%D1%8B%D1%80%D0%B0.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 7287,
    height: 4099,
    category: "landscape",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 winners",
    quoteId: "old-stone",
  }),
  curated({
    id: "zoom-wle-savsat-autumn",
    title: "Savsat autumn forest",
    author: "Turreis10700",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C5%9Eav%C5%9Fatta_Sonbahar.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/%C5%9Eav%C5%9Fatta_Sonbahar.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/%C5%9Eav%C5%9Fatta_Sonbahar.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 4104,
    height: 2672,
    category: "landscape",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 winners",
    quoteId: "mountain-rain",
  }),
  curated({
    id: "zoom-wle-fusine-lake",
    title: "Lago di Fusine reflection",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Riflesso_al_Lago_di_Fusine.jpg",
    imageUrl: "/assets/wallpapers/zoom-wle-fusine-lake.jpg",
    thumbnailUrl: "/assets/wallpapers/zoom-wle-fusine-lake.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 3000,
    height: 1865,
    category: "landscape",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 winners",
    quoteId: "water-still",
  }),
  curated({
    id: "zoom-wle-kerkennah-dawn",
    title: "Fisherman returning at dawn, Kerkennah",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Un_pecheur_rentre_au_port_au_lever_du_jour_%C3%A0_kerkennah_-_vue_large_-_tunisie.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Un_pecheur_rentre_au_port_au_lever_du_jour_%C3%A0_kerkennah_-_vue_large_-_tunisie.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Un_pecheur_rentre_au_port_au_lever_du_jour_%C3%A0_kerkennah_-_vue_large_-_tunisie.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 8980,
    height: 5987,
    category: "ocean",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 winners",
    quoteId: "water-still",
  }),
  curated({
    id: "zoom-wle-deer-mist",
    title: "A deer in the mist",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_deer_in_the_mist.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f3/A_deer_in_the_mist.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f3/A_deer_in_the_mist.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 3000,
    height: 2000,
    category: "animals",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 winners",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-wle-hoopoe-feeding",
    title: "Hoopoe feeding young",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dudek_chocholat%C3%BD_p%C5%99i_krmen%C3%AD_ml%C3%A1%C4%8Fat.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Dudek_chocholat%C3%BD_p%C5%99i_krmen%C3%AD_ml%C3%A1%C4%8Fat.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Dudek_chocholat%C3%BD_p%C5%99i_krmen%C3%AD_ml%C3%A1%C4%8Fat.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 5231,
    height: 3558,
    category: "animals",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 winners",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-featured-golden-eagle-majinghorn",
    title: "Golden eagle over Majinghorn",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:001_Wild_Golden_Eagle_and_Majinghorn_Pfyn-Finges_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/001_Wild_Golden_Eagle_and_Majinghorn_Pfyn-Finges_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/001_Wild_Golden_Eagle_and_Majinghorn_Pfyn-Finges_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 8640,
    height: 4719,
    category: "animals",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen / Wiki Loves Earth",
    quoteId: "wide-sky",
  }),
  curated({
    id: "zoom-featured-ibex-swiss-alps",
    title: "Alpine ibex in the Swiss Alps",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:002_Wild_Alpine_Ibex_Swiss_Alps_and_Creux_du_Van_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ea/002_Wild_Alpine_Ibex_Swiss_Alps_and_Creux_du_Van_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ea/002_Wild_Alpine_Ibex_Swiss_Alps_and_Creux_du_Van_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 7533,
    height: 5022,
    category: "animals",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen / Wiki Loves Earth",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-featured-jakobshavn-glacier",
    title: "Aerial view of Jakobshavn Glacier",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:023_Aerial_view_of_Jakobshavn_Glacier_at_Disko_Bay_(Greenland)_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/023_Aerial_view_of_Jakobshavn_Glacier_at_Disko_Bay_%28Greenland%29_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/023_Aerial_view_of_Jakobshavn_Glacier_at_Disko_Bay_%28Greenland%29_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 5472,
    height: 3648,
    category: "aerial",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen / Wiki Science Competition",
    quoteId: "water-still",
  }),
  curated({
    id: "zoom-featured-lake-louise",
    title: "Lake Louise panorama",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1_lake_louise_pano_2019.jpg",
    imageUrl: "/assets/wallpapers/zoom-featured-lake-louise.jpg",
    thumbnailUrl: "/assets/wallpapers/zoom-featured-lake-louise.jpg",
    license: "Creative Commons / Wikimedia Commons",
    width: 14102,
    height: 7912,
    category: "landscape",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen",
    quoteId: "water-still",
  }),
  curated({
    id: "zoom-featured-lofoten-bridge",
    title: "Lofoten bridge between Sakrisoya and Andoya",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:0688_Norway_Lofoten_bridge_between_Sakrisoya_and_Andoya.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/0688_Norway_Lofoten_bridge_between_Sakrisoya_and_Andoya.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/0688_Norway_Lofoten_bridge_between_Sakrisoya_and_Andoya.jpg",
    license: "Creative Commons / Wikimedia Commons",
    width: 7609,
    height: 4280,
    category: "landmark",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen",
    quoteId: "mountain-rain",
  }),
  curated({
    id: "zoom-featured-taipei-sunrise",
    title: "Taipei sunrise panorama",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1_taipei_sunrise_panorama_dxr_edit_pangen_141215_1.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e4/1_taipei_sunrise_panorama_dxr_edit_pangen_141215_1.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e4/1_taipei_sunrise_panorama_dxr_edit_pangen_141215_1.jpg",
    license: "Creative Commons / Wikimedia Commons",
    width: 8871,
    height: 5003,
    category: "landmark",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen",
    quoteId: "city-dawn",
  }),
  curated({
    id: "zoom-featured-calanche-piana",
    title: "Calanche de Piana cliffs",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:01_Calanche_Piana.jpg",
    imageUrl: "/assets/wallpapers/zoom-featured-calanche-piana.jpg",
    thumbnailUrl: "/assets/wallpapers/zoom-featured-calanche-piana.jpg",
    license: "Creative Commons / Wikimedia Commons",
    width: 4032,
    height: 2636,
    category: "landscape",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen",
    quoteId: "mountain-rain",
  }),
  curated({
    id: "zoom-featured-gorges-du-tarn",
    title: "Gorges du Tarn at Roc des Hourtous",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:01_Gorges_du_Tarn_Roc_des_Hourtous.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/54/01_Gorges_du_Tarn_Roc_des_Hourtous.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/5/54/01_Gorges_du_Tarn_Roc_des_Hourtous.jpg",
    license: "Creative Commons / Wikimedia Commons",
    width: 4288,
    height: 2848,
    category: "landscape",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen",
    quoteId: "mountain-rain",
  }),
  curated({
    id: "zoom-wlm-frauenkirche-munich",
    title: "Frauenkirche Munich",
    author: "Martin Falbisoner",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Frauenkirche_Munich_March_2013.JPG",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Frauenkirche_Munich_March_2013.JPG",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Frauenkirche_Munich_March_2013.JPG",
    license: "Creative Commons Attribution-Share Alike 3.0",
    width: 5415,
    height: 3610,
    category: "landmark",
    quality: "featured",
    sourceCollection: "Wiki Loves Monuments / Wikimedia Featured Pictures",
    quoteId: "city-dawn",
  }),
  curated({
    id: "zoom-wlm-mercado-do-bolhao",
    title: "Mercado do Bolhao",
    author: "Wikimedia Commons contributor",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1_Mercado_do_Bolh%C3%A3o.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/1_Mercado_do_Bolh%C3%A3o.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/1_Mercado_do_Bolh%C3%A3o.jpg",
    license: "Creative Commons / Wikimedia Commons",
    width: 6135,
    height: 4090,
    category: "landmark",
    quality: "featured",
    sourceCollection: "Wiki Loves Monuments / Wikimedia Featured Widescreen",
    quoteId: "city-dawn",
  }),
  curated({
    id: "zoom-featured-wind-mountain",
    title: "Wind Mountain, Columbia River",
    author: "James Madison Alden / National Archives",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%22Wind_Mountain%22_Columbia_R_-_NARA_-_102278851_(page_1).png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a3/%22Wind_Mountain%22_Columbia_R_-_NARA_-_102278851_%28page_1%29.png",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a3/%22Wind_Mountain%22_Columbia_R_-_NARA_-_102278851_%28page_1%29.png",
    license: "Public domain / National Archives",
    width: 5609,
    height: 3597,
    category: "landscape",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Pictures public domain",
    quoteId: "old-stone",
  }),
  curated({
    id: "zoom-usgs-lava-fountain-dome",
    title: "Lava fountain dome, Kilauea",
    author: "J. B. Judd / USGS",
    source: "usgs",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lava_fountain_dome_2.jpg",
    imageUrl: "/assets/wallpapers/zoom-usgs-lava-fountain-dome.jpg",
    thumbnailUrl: "/assets/wallpapers/zoom-usgs-lava-fountain-dome.jpg",
    license: "Public domain / USGS",
    width: 5194,
    height: 3471,
    category: "weather",
    quality: "curated",
    sourceCollection: "USGS Multimedia Gallery / Wikimedia Commons",
    quoteId: "earth-fire",
  }),
  curated({
    id: "zoom-featured-lava-wildfire",
    title: "Kilauea lava wildfire from the air",
    author: "Brocken Inaglory",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lava_wildfire.JPG",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Lava_wildfire.JPG",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Lava_wildfire.JPG",
    license: "Creative Commons Attribution-Share Alike 3.0",
    width: 3888,
    height: 2592,
    category: "aerial",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen",
    quoteId: "earth-fire",
  }),
  curated({
    id: "zoom-featured-pahoehoe-lava",
    title: "Pahoehoe lava flow",
    author: "Brocken Inaglory",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:P%C4%81hoehoe_Lava_flow.JPG",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b1/P%C4%81hoehoe_Lava_flow.JPG",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b1/P%C4%81hoehoe_Lava_flow.JPG",
    license: "Creative Commons Attribution-Share Alike 3.0",
    width: 3888,
    height: 2592,
    category: "weather",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Pictures / Picture of the Year",
    quoteId: "earth-fire",
  }),
  curated({
    id: "zoom-featured-golden-jackal",
    title: "Golden jackal in Jim Corbett National Park",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:001_Golden_jackal_and_azureum_flowers_in_Jim_Corbett_National_Park_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/98/001_Golden_jackal_and_azureum_flowers_in_Jim_Corbett_National_Park_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/9/98/001_Golden_jackal_and_azureum_flowers_in_Jim_Corbett_National_Park_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 7850,
    height: 5233,
    category: "animals",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen / Wiki Loves Earth",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-featured-great-blue-turaco",
    title: "Great blue turaco at Kibale Forest",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:017_Great_blue_turaco_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/017_Great_blue_turaco_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/017_Great_blue_turaco_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 4413,
    height: 2942,
    category: "animals",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen / Wiki Loves Earth",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-wle-lilac-breasted-roller",
    title: "Lilac-breasted roller in Serengeti",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:018_Lilac-breasted_roller_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/018_Lilac-breasted_roller_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/018_Lilac-breasted_roller_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 5505,
    height: 3670,
    category: "animals",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 / Featured Pictures",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-wle-grants-gazelle",
    title: "Grant's gazelle in Serengeti",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:022_Grant%27s_gazelle_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/022_Grant%27s_gazelle_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/022_Grant%27s_gazelle_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 8502,
    height: 5668,
    category: "animals",
    quality: "award",
    sourceCollection: "Wiki Loves Earth 2024 / Featured Pictures",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-featured-flamingos-camargue",
    title: "Greater flamingos in the Camargue",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:010_Greater_flamingos_male_and_female_in_the_Camargue_during_mating_season_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/81/010_Greater_flamingos_male_and_female_in_the_Camargue_during_mating_season_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/8/81/010_Greater_flamingos_male_and_female_in_the_Camargue_during_mating_season_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 6429,
    height: 4286,
    category: "animals",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-featured-lioness-golden-hour",
    title: "Lioness at golden hour",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:048_Lioness_during_golden_hour_of_the_morning_at_Queen_Elizabeth_National_Park_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/79/048_Lioness_during_golden_hour_of_the_morning_at_Queen_Elizabeth_National_Park_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/7/79/048_Lioness_during_golden_hour_of_the_morning_at_Queen_Elizabeth_National_Park_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 8640,
    height: 5760,
    category: "animals",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen / Wiki Loves Earth",
    quoteId: "patient-life",
  }),
  curated({
    id: "zoom-featured-african-wolf",
    title: "African wolf in Serengeti",
    author: "Giles Laurent",
    source: "wikimedia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:023_African_wolf_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e1/023_African_wolf_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e1/023_African_wolf_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    license: "Creative Commons Attribution-Share Alike 4.0",
    width: 5154,
    height: 3436,
    category: "animals",
    quality: "featured",
    sourceCollection: "Wikimedia Featured Widescreen / Wiki Loves Earth",
    quoteId: "patient-life",
  }),
];
